baseURL: https://luftfart.github.io/
languageCode: nb-NO
title: Luftfart
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Vil du lære om fly ✈️👋?
        Content: Kule ting om hvordan fly fungerer, forskjellige flytyper og NYHETER OM REISE OG LUFTFART 

    socialIcons: # optional
        - name: "youtube"
          url: "https://www.youtube.com/@minfuel"
        - name: "twitter"
          url: "https://twitter.com/minfuel"
        - name: "kofi" 
          url: "https://buymeacoffee.com/minfuel"
        - name: "rss"
          url: "https://aryansawhney.com/index.xml"
    ShowReadingTime: true
    author: "Flymekanikk student"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20